import { GeistSans } from "geist/font/sans";
import { type AppType } from "next/app";
import { Toaster } from "react-hot-toast";
import airtableLogo from "src/images/Airtable-Logo-cropped.jpg";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import Head from "next/head";
import { ChakraProvider, defaultSystem } from "@chakra-ui/react";
import Image from "next/image";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ChakraProvider value={defaultSystem}>
      <ClerkProvider>
        <Head>
          <title>airtableclone</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SignedOut>
          <div className="flex h-screen w-screen items-start justify-center bg-[#f2f2f2]">
            <div className="mt-44 flex h-64 flex-col rounded-lg border bg-white">
              <Image
                src={airtableLogo}
                alt="airtable logo"
                className="m-5 h-[64px] w-[243.2px]"
              />
              <span className="text-center text-xl">Welcome</span>
              <SignInButton>
                <button
                  type="button"
                  className="mx-8 mt-7 rounded-full bg-sky-500 py-2 hover:bg-sky-700"
                >
                  Sign in to continue
                </button>
              </SignInButton>
            </div>
          </div>
        </SignedOut>
        <SignedIn>
          <div style={{ fontFamily: `"Segoe UI", Tahoma, Geneva, Verdana, sans-serif`, fontSize: 13 }}>
            <Toaster position="bottom-center" />
            <Component {...pageProps} />
          </div>
        </SignedIn>
      </ClerkProvider>
    </ChakraProvider>
  );
};

export default api.withTRPC(MyApp);
